// packages/webui-solid/src/DiceCost.tsx
import type { DiceType } from "@gi-tcg/typings";
import { For, JSX, splitProps } from "solid-js";

import { Dice } from "./Dice";

interface DiceCostProps extends JSX.HTMLAttributes<HTMLDivElement> {
  cost: DiceType[];
  realCost?: DiceType[];
}

function diceToMap(dice: readonly DiceType[]): Map<DiceType, number> {
  const result = new Map<DiceType, number>();
  for (const d of dice) {
    result.set(d, (result.get(d) ?? 0) + 1);
  }
  return result;
}

export function DiceCost(props: DiceCostProps) {
  const [local, restProps] = splitProps(props, ["cost", "realCost"]);
  const diceMap = () => [...diceToMap(local.cost).entries()];
  return (
    <div {...restProps}>
      <For each={diceMap()}>
        {([type, count]) => <Dice type={type} text={`${count}`} size={30} />}
      </For>
    </div>
  );
}

// packages/webui/src/components/dice_cost.tsx
import type { DiceType } from "@gi-tcg/typings";
import { JSX } from "preact";
import { useMemo } from "preact/hooks";
import { Dice } from "./dice";

interface DiceCostProps extends JSX.HTMLAttributes<HTMLDivElement> {
  cost: DiceType[];
  realCost?: DiceType[];
}

function diceToMap(dice: readonly DiceType[]): Map<DiceType, number> {
  const result = new Map<DiceType, number>();
  for (const d of dice) {
    result.set(d, (result.get(d) ?? 0) + 1);
  }
  return result;
}

export function DiceCost({ cost, realCost = cost, ...props }: DiceCostProps) {
  const diceMap = useMemo(() => [...diceToMap(cost).entries()], [cost]);
  return (
    <div {...props}>
      {diceMap.map(([type, count], i) => (
        <Dice key={i} type={type} text={`${count}`} size={30} />
      ))}
    </div>
  );
}
