// packages/webui-core/src/DiceCost.tsx
import type { DiceType } from "@gi-tcg/typings";
import { diceToMap } from "@gi-tcg/utils";
import { ComponentProps, For, splitProps } from "solid-js";

import { Dice, DiceColor } from "./Dice";

interface DiceCostProps extends ComponentProps<"div"> {
  cost: readonly DiceType[];
  realCost?: readonly DiceType[];
}

export function DiceCost(props: DiceCostProps) {
  const [local, restProps] = splitProps(props, ["cost", "realCost"]);
  const diceMap = () => {
    const costMap = diceToMap(local.cost);
    let result: [type: DiceType, count: number, color: DiceColor][] = [];
    if (local.realCost) {
      const realCostMap = diceToMap(local.realCost);
      const allCostType = new Set([...local.cost, ...local.realCost]);
      for (const type of allCostType) {
        const realCount = realCostMap.get(type) ?? 0;
        const originalCount = costMap.get(type) ?? 0;
        const color =
        realCount > originalCount
            ? "increased"
            : realCount < originalCount
              ? "decreased"
              : "normal";
        result.push([type, realCount, color]);
      }
    } else {
      result = [...costMap.entries()].map(([type, count]) => [
        type,
        count,
        "normal",
      ]);
    }
    return result;
  };
  return (
    <div {...restProps}>
      <For each={diceMap()}>
        {([type, count, color]) => (
          <Dice type={type} text={`${count}`} size={30} color={color} />
        )}
      </For>
    </div>
  );
}

// packages/webui/src/components/dice_cost.tsx
import type { DiceType } from "@gi-tcg/typings";
import { JSX } from "preact";
import { useMemo } from "preact/hooks";
import { Dice } from "./dice";

interface DiceCostProps extends JSX.HTMLAttributes<HTMLDivElement> {
  cost: DiceType[];
  realCost?: DiceType[];
}

function diceToMap(dice: readonly DiceType[]): Map<DiceType, number> {
  const result = new Map<DiceType, number>();
  for (const d of dice) {
    result.set(d, (result.get(d) ?? 0) + 1);
  }
  return result;
}

export function DiceCost({ cost, realCost = cost, ...props }: DiceCostProps) {
  const diceMap = useMemo(() => [...diceToMap(cost).entries()], [cost]);
  return (
    <div {...props}>
      {diceMap.map(([type, count], i) => (
        <Dice key={i} type={type} text={`${count}`} size={30} />
      ))}
    </div>
  );
}
