// packages/webui-core/src/Image.tsx
import { ComponentProps, Show, createResource, splitProps } from "solid-js";
import { usePlayerContext } from "./Chessboard";

export interface ImageProps extends ComponentProps<"img"> {
  imageId: number;
}

const cachedObjectUrls = new Map<string, string>();
async function cachedFetch(url: string): Promise<string> {
  if (cachedObjectUrls.has(url)) {
    return cachedObjectUrls.get(url)!;
  }
  return fetch(url)
    .then((r) => r.blob())
    .then((blob) => {
      const objectUrl = URL.createObjectURL(blob);
      cachedObjectUrls.set(url, objectUrl);
      return objectUrl;
    });
}

export function Image(props: ImageProps) {
  const [local, rest] = splitProps(props, ["imageId", "width", "height"]);
  const { assetApiEndpoint } = usePlayerContext();
  const [url] = createResource(() => cachedFetch(`${assetApiEndpoint}/images/${local.imageId}`));
  const classNames = "flex items-center justify-center object-cover";
  const innerProps = (): ComponentProps<"img"> => ({
    ...rest,
    class: `${rest.class ?? ""} ${classNames}`,
    src: url(),
    alt: `id = ${local.imageId}`,
    draggable: "false",
    style: {
      background: url.state === "ready" ? void 0 : "#e5e7eb",
      height: local.height ? `${local.height}px` : void 0,
      width: local.width ? `${local.width}px` : void 0,
    },
  });
  return (
    <Show
      when={url.state === "ready"}
      fallback={
        <div {...(innerProps() as ComponentProps<"div">)}>{local.imageId}</div>
      }
    >
      <img {...innerProps()} />
    </Show>
  );
}

// packages/webui/src/components/image.tsx
import { type JSX } from "preact";
import { type Signal, signal } from "@preact/signals";
import { getAssetPath } from "../config";

export interface ImageProps extends JSX.HTMLAttributes<HTMLDivElement> {
  imageId: number;
}

const allAssets = new Map<number, Signal<string | null>>();

function useImageAsset(imageId: number) {
  if (allAssets.has(imageId)) {
    return allAssets.get(imageId)!;
  }
  const newImage = signal<string | null>(null);
  allAssets.set(imageId, newImage);
  const assetUrl = getAssetPath(imageId);
  if (assetUrl !== null) {
    fetch(assetUrl)
      .then((r) => r.blob())
      .then((blob) => {
        newImage.value = URL.createObjectURL(blob);
      });
  }
  return newImage;
}

export function Image({ imageId, ...props }: ImageProps) {
  const url = useImageAsset(imageId);
  return (
    <div class={props.class}>
      {(url.value !== null && (
        <img src={url.value} alt={`id = ${imageId}`} />
      )) || (
        <div class="w-full h-full bg-gray-200 flex items-center justify-center">
          {imageId}
        </div>
      )}
    </div>
  );
}
