// packages/webui-solid/src/Card.tsx
import type { CardData } from "@gi-tcg/typings";

import "./Card.css";

import { Image } from "./Image";
import { DiceCost } from "./DiceCost";
import { usePlayerContext } from "./Chessboard";
import { Show } from "solid-js";

export interface CardProps {
  data: CardData;
}

export function Card(props: CardProps) {
  const { allClickable, allSelected } = usePlayerContext();
  const draggable = false; // TODO
  const selected = () => allSelected().includes(props.data.id);
  const clickable = () => allClickable().includes(props.data.id);
  return (
    <div class="card-wrapper">
      <Show
        when={props.data.definitionId > 0}
        fallback={
          <div class="h-full aspect-[7/12] rotated flex items-center justify-center bg-gray-600 b-gray-700 b-solid b-4 color-white rounded" />
        }
      >
        <div
          class="card relative"
          classList={{ selected: selected() }}
          // @click="clickable && emit('click', data.id)"
          // </div>@dragstart="dragstartHandler"
          // @dragend="dragendHandler"
          draggable={draggable}
        >
          <Image
            imageId={props.data.definitionId}
            class="h-full rounded-lg shadow-lg"
            classList={{ clickable: clickable() }}
            title={`id = ${props.data.id}`}
          />
          <DiceCost
            class="absolute left-0 top-0 translate-x-[-50%] flex flex-col"
            cost={props.data.definitionCost}
          />
        </div>
      </Show>
    </div>
  );
}

// packages/standalone/src/components/Card.vue
<script lang="ts" setup>
import { computed } from "vue";
import { CardData } from "@gi-tcg/typings";
import {} from "@gi-tcg/utils";

import Image from "./Image.vue";
import { costData } from "../static_data";
import Dice from "./Dice.vue";

const props = defineProps<{
  data: CardData;
  clickable?: boolean;
  draggable?: boolean;
  selected?: boolean;
}>();

const emit = defineEmits<{
  click: [id: number];
  dragstart: [id: number];
  dragend: [id: number];
}>();

const cardCost = computed(() => costData[props.data.definitionId]);

function dragstartHandler(e: DragEvent) {
  e.dataTransfer!.setData("text/plain", props.data.id.toString());
  emit("dragstart", props.data.id);
}
function dragendHandler(e: DragEvent) {
  emit("dragend", props.data.id);
}
</script>

<template>
  <div class="card-wrapper">
    <div
      class="card relative"
      v-if="data.definitionId > 0"
      :class="{ selected }"
      @click="clickable && emit('click', data.id)"
      @dragstart="dragstartHandler"
      @dragend="dragendHandler"
      :draggable="draggable"
    >
      <Image
        :id="data.definitionId"
        class="h-full rounded-lg shadow-lg"
        :class="{ clickable }"
        :title="`id = ${data.id}`"
      ></Image>
      <div class="absolute left-0 top-0 translate-x-[-50%] flex flex-col">
        <Dice
          v-for="[dt, val] of cardCost"
          :value="dt"
          :text="`${val}`"
          :size="30"
        ></Dice>
      </div>
    </div>
    <div
      v-else
      class="h-full aspect-[7/12] rotated flex items-center justify-center bg-gray-600 b-gray-700 b-solid b-4 color-white rounded"
    >
      ?
    </div>
  </div>
</template>

<style>
.hands-area {
  .card-wrapper {
    height: 100%;
    perspective: 800px;
    aspect-ratio: 1/2;
    transition: all 0.3s;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .card-wrapper:has(.card):hover,
  .card-wrapper:has(.selected) {
    aspect-ratio: 1/1;
  }
  .card-wrapper:hover > .card,
  .card-wrapper > .selected {
    transform: none;
    transition: all 0.3s;
  }

  .card {
    height: 100%;
    transform: rotate3d(0, 1, 0, 30deg);
    transition: all 0.3s;
  }
  .rotated {
    transform: rotate3d(0, 1, 0, 30deg);
  }
}
</style>
