// packages/webui-solid/src/SkillButton.tsx
import { DiceType, SkillData } from "@gi-tcg/typings";
import { Image } from "./Image";
import { Index } from "solid-js";
import { DiceCost } from "./DiceCost";
import { usePlayerContext } from "./Chessboard";

export interface SkillButtonProps {
  data: SkillData;
}

export function SkillButton(props: SkillButtonProps) {
  const { allClickable, onClick, allCosts } = usePlayerContext();
  const clickable = () => allClickable.includes(props.data.definitionId);
  const realCost = () => allCosts[props.data.definitionId];
  return (
    <div class="flex flex-col items-center">
      <button
        type="button"
        class="w-10 h-10 rounded-999 bg-yellow-800 p-1 border-none disabled:opacity-50 hover:bg-yellow-700 active:bg-yellow-900 transition-all disabled:bg-yellow-700 flex items-center justify-center"
        disabled={!clickable()}
        onClick={() => clickable() && onClick(props.data.definitionId)}
      >
        <Image imageId={props.data.definitionId} class="object-contain" />
      </button>
      <DiceCost
        class="flex flex-row"
        cost={props.data.definitionCost}
        realCost={realCost()}
      />
    </div>
  );
}

// packages/standalone/src/components/SkillButton.vue
<script lang="ts" setup>
import { computed } from "vue";
import Image from "./Image.vue";
import { costData } from "../static_data";
import Dice from "./Dice.vue";

const props = defineProps<{
  id: number;
  enabled: boolean;
}>();

const cardCost = computed(() => costData[props.id]);
</script>

<template>
  <div class="flex flex-col items-center">
    <button
      type="button"
      class="w-10 h-10 rounded-999 bg-yellow-800 p-1 border-none disabled:opacity-50 hover:bg-yellow-700 active:bg-yellow-900 transition-all disabled:bg-yellow-700"
      :disabled="!enabled"
    >
      <Image :id="id" class="object-contain"></Image>
    </button>
    <div class="flex flex-row">
      <Dice
        v-for="[dt, val] of cardCost"
        :value="dt"
        :text="`${val}`"
      ></Dice>
    </div>
  </div>
</template>
