// packages/webui/src/components/image.tsx
import { type JSX } from "preact";
import { type Signal, signal } from "@preact/signals";
import { getAssetPath } from "../config";
import { useMemo } from "preact/hooks";

export interface ImageProps extends JSX.HTMLAttributes<HTMLDivElement> {
  imageId: number;
}

const allAssets = new Map<number, Signal<string | null>>();

function tryFetch(url: string, target: Signal<string | null>, retry = 5) {
  fetch(url)
    .then((r) => r.blob())
    .then((blob) => {
      target.value = URL.createObjectURL(blob);
    })
    .catch(() =>
      setTimeout(() => retry > 0 && tryFetch(url, target, retry - 1), 500),
    );
}

function useImageAsset(imageId: number) {
  return useMemo(() => {
    if (allAssets.has(imageId)) {
      return allAssets.get(imageId)!;
    }
    const newImage = signal<string | null>(null);
    allAssets.set(imageId, newImage);
    const assetUrl = getAssetPath(imageId);
    if (assetUrl !== null) {
      tryFetch(assetUrl, newImage);
    }
    return newImage;
  }, [imageId]);
}

export function Image({ imageId, ...props }: ImageProps) {
  const url = useImageAsset(imageId);
  return (
    <div {...props}>
      {url.value !== null ? (
        <img src={url.value} alt={`id = ${imageId}`} draggable={false} />
      ) : (
        <div class="w-full h-full bg-gray-200 flex items-center justify-center">
          {imageId}
        </div>
      )}
    </div>
  );
}

// packages/webui-solid/src/Image.tsx
import { JSX, createResource, splitProps } from "solid-js";

import { getAssetPath } from "./config";

export interface ImageProps extends JSX.HTMLAttributes<HTMLDivElement> {
  imageId: number;
  width?: number;
}

const allAssets = new Map<number, string>();
async function tryFetch(imageId: number, retry = 5): Promise<string> {
  if (allAssets.has(imageId)) {
    return allAssets.get(imageId)!;
  }
  const assetUrl = getAssetPath(imageId);
  if (assetUrl === null) {
    return Promise.reject("asset url not found");
  }
  if (retry <= 0) {
    return Promise.reject("retry exhausted");
  }
  return fetch(assetUrl)
    .then((r) => r.blob())
    .then((blob) => {
      const objectUrl = URL.createObjectURL(blob);
      allAssets.set(imageId, objectUrl);
      return objectUrl;
    })
    .catch(() => tryFetch(imageId, retry - 1));
}

export function Image(props: ImageProps) {
  const [local, restProps] = splitProps(props, ["imageId", "width"]);
  const [url] = createResource(() => tryFetch(local.imageId));
  return (
    <div
      {...restProps}
      style={{ width: local.width ? `${local.width}px` : void 0 }}
    >
      {url.state === "ready" ? (
        <img src={url()} alt={`id = ${local.imageId}`} draggable={false} />
      ) : (
        <div class="w-full h-full bg-gray-200 flex items-center justify-center">
          {local.imageId}
        </div>
      )}
    </div>
  );
}
