// packages/standalone-new/src/components/PlayerArea.vue
<script lang="ts" setup>
import { PlayerData } from "@gi-tcg/typings";
import CharacterArea from "./CharacterArea.vue";
import Summon from "./Summon.vue";
import Support from "./Support.vue";
import Card from "./Card.vue";
import Dice from "./Dice.vue";

const props = defineProps<{
  data: PlayerData;
}>();
</script>

<template>
  <div class="flex flex-row">
    <div>{{ data.piles.length }}</div>
    <div class="flex flex-col">
      <div class="flex flex-row">
        <div>
          <Support
            v-for="support of data.supports"
            :key="support.id"
            :data="support"
          ></Support>
        </div>
        <div>
          <CharacterArea
            v-for="ch of data.characters"
            :key="ch.id"
          ></CharacterArea>
        </div>
        <div>
          <Summon
            v-for="summon of data.summons"
            :key="summon.id"
            :data="summon"
          ></Summon>
        </div>
      </div>
      <div class="flex flex-row">
        <Card v-for="card of data.hands" :key="card.id" :data="card"></Card>
      </div>
    </div>
    <div>
      <Dice v-for="d of data.dice" :value="d"></Dice>
    </div>
  </div>
</template>

// packages/webui-solid/src/PlayerArea.tsx
import type { PlayerData } from "@gi-tcg/typings";
import { For } from "solid-js";

import { Summon, Support, Status } from "./Entity";
import { CharacterArea } from "./CharacterArea";
import { Card } from "./Card";

export interface PlayerAreaProps {
  data: PlayerData;
  opp: boolean;
}

export function PlayerArea(props: PlayerAreaProps) {
  return (
    <div class="w-full flex flex-row">
      <div class="bg-yellow-800 text-white flex items-center w-10 flex-shrink-0">
        piles = {props.data.piles.length}
      </div>
      <div
        class={`flex-grow flex gap-6 ${
          props.opp ? "flex-col-reverse" : "flex-col"
        }`}
      >
        <div class="h-52 flex flex-row justify-center gap-6">
          <div class="min-w-40">
            <For each={props.data.supports}>
              {(support) => <Support data={support} />}
            </For>
          </div>
          <div class="flex flex-row gap-6 items-end">
            <For each={props.data.characters}>
              {(ch) => (
                <div class="flex flex-col">
                  <CharacterArea data={ch} />
                  {ch.id === props.data.activeCharacterId ? (
                    <div class="h-6 flex flex-row">
                      <For each={props.data.combatStatuses}>
                        {(st) => <Status data={st} />}
                      </For>
                    </div>
                  ) : (
                    props.opp && <div class="h-12" />
                  )}
                </div>
              )}
            </For>
          </div>
          <div class="min-w-40">
            <For each={props.data.summons}>
              {(summon) => <Summon data={summon} />}
            </For>
          </div>
        </div>
        <div
          class={`h-30 flex flex-row mx-4 hands-area ${
            props.opp ? "justify-end" : "justify-start"
          }`}
        >
          <For each={props.data.hands}>
            {(card) => (
              <Card
                data={card}
                // onDragstart={onDragstart}
                // onDragend={ondragend}
              />
            )}
          </For>
        </div>
      </div>
    </div>
  );
}
